name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 212.67.15.105
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/bitrix/www
            git pull origin main
            echo "Deployment successful!"
